kind: Service
apiVersion: v1
metadata:
  name: bank-account
  labels:
    name: bank-account
spec:
  ports:
    - nodePort: 30170
      port: 80
      targetPort: 9003
      protocol: TCP
  selector:
    app: bank-account
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-account
spec:
  selector:
    matchLabels:
      app: bank-account
  replicas: 2
  template:
    metadata:
      labels:
        app: bank-account
    spec:
      containers:
        - name: bank-account
          image: priyagiri/bankaccount-service:3.0
          ports:
            - containerPort: 9003
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-user # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password