kind: Service
apiVersion: v1
metadata:
  name: paypal
  labels:
    name: paypal
spec:
  ports:
    - nodePort: 30166
      port: 80
      targetPort: 9002
      protocol: TCP
  selector:
    app: paypal
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal
spec:
  selector:
    matchLabels:
      app: paypal
  replicas: 2
  template:
    metadata:
      labels:
        app: paypal
    spec:
      containers:
        - name: paypal
          image: priyagiri/paypal-service:1.0
          ports:
            - containerPort: 9002
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-user # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password