kind: Service
apiVersion: v1
metadata:
  name: transaction
  labels:
    name: transaction
spec:
  ports:
    - nodePort: 30163
      port: 80
      targetPort: 9005
      protocol: TCP
  selector:
    app: transaction
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  selector:
    matchLabels:
      app: transaction
  replicas: 2
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction
          image: priyagiri/transaction-service:1.0
          ports:
            - containerPort: 9005
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-user # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password
